### ISSUE TITLE
Support PKI auth against upstream proxy server [enhancement]

### ISSUE THREAD

**Issue by jrgp** [browserup/browserup-proxy#106]
**Is your feature request related to a problem? Please describe.**

In our use case, we'd like to be able to authenticate with an upstream https proxy server using PKI, and providing a client side certificate (which we'd generate on our end). 

**Describe the solution you'd like**

It would be great if, while specifying the URL of an optional upstream proxy during har creation, we could also specify paths to a client side certificate/private key files (or just a single .jks file) which browserup would then provide as authentication to an upstream proxy.

Would something like this be feasible?

**Comment by ericbeland** [comment]
Would this be for the embedded mode? Would it work through the REST API?  What would the behavior be when the proxy is remote?

**Comment by jrgp** [comment]
Thanks for following up. Sorry for not really clarifying.

This would be for when browserup runs as a standalone java app and exposes its rest API.

Behavior is currently:

Selenium firefox/etc -> browserup-proxy -> (our upstream proxy with no auth) -> internet

Proposed behavior:

Selenium firefox/etc -> browserup-proxy -> (an upstream proxy, requiring PKI auth) -> internet

It could be possible to configure browserup-proxy to always hit https endpoints using PKI by adding the `-Djavax.net.ssl.keyStore=` and `-Djavax.net.ssl.keyStorePassword` flags, but my concern there is it would use those flags when hitting the sites we're testing with selenium, in addition to the upstream proxy.

**Comment by jrgp** [comment]
Hey, my security requirements changed and I no longer need this functionality. This can be closed.

**Comment by ericbeland** [comment]
Hi Joe,

Thanks for the heads up! I did look into it a bit, although I didn't finish scoping out what would be involved. We could probably have gotten to it, but not for a month or two. If you see something else that make sense, let us know!
