### ISSUE TITLE
Bad Request due to allowRequestToOriginServer == false

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [browserup/browserup-proxy#108]
**Describe the bug**
I'm using browserup-proxy embedded in a spring boot application. I can successfully create and start the proxy server:

```
@Bean
public BrowserUpProxy proxy() throws IOException {
    BrowserUpProxy proxy = new BrowserUpProxyServer();
    proxy.setMitmManager(impersonatingMitmManager());
    proxy.start(proxyPort);
    return proxy;
}
```

> Starting proxy at address: 0.0.0.0/0.0.0.0:8401 : MDC[]
> Initializing thread pools for TCP with 2 acceptor threads, 8 incoming worker threads, and 8 outgoing worker threads : MDC[]
> Proxy listening with TCP transport : MDC[]
> Proxy started at address: /0:0:0:0:0:0:0:0:8401 : MDC[]

When I make a REST call to create a proxy I get a Bad Request:

```
$ curl -X POST http://127.0.0.1:8401/proxy
Bad Request to URI: /
```

Setting a break point in ClientToProxyConnection I see the bad request is coming because `!proxyServer.isAllowRequestsToOriginServer() && isRequestToOriginServer(httpRequest)` is true.

How do I allow requests to the origin server?

**Comment by ericbeland** [comment]
I admit to being a bit confused about your use-case. We have the browserup proxy REST artifact that you can spin up and talk to directly via it's REST API. It seems like maybe you are looking for something like that, but instead are wiring it up yourself? 

Alternately, maybe you're embedding the proxy in an app to capture a har from the same app? Or is there something else going on I haven't understood like reverse proxying?

The clientToProxy code is in littleproxy, which we wrap and use for our communication, but that's a separate project.

**Comment by Blackbaud-JasonBodnar** [comment]
I'm building a proxy that will allow our employees to test and demo different behavior in front end web applications. The idea is an employee will log into this service. (It will have it's own REST-based front end.) The back end will create a new proxy for the user (or use an existing one) and return the port number of the proxy. The employee will set their OS/browser/browser extension to use that proxy and tell the front end to start recording traffic. The traffic (HAR data) will be returned to the front end where the employee can view it and create rules to change the server responses (status codes, response bodies) for specific method calls. When the employee's browser makes that call again the response returned will be changed based on the rules.

This will allow us to create error situations or simulate different data sets to test or demo how the front ends handle them.

________________________________

**Comment by ericbeland** [comment]
Interesting use-case!

Normally, that littleproxy setting isn't something that needs to be tweaked, so I don't have much to offer there.  I'm not sure why that would be coming up or if it is a red herring.

I'm not clear on the lifecycle of a Spring request/response bean. Usually in web apps the work done in an action like that would be short lived and the embedded proxy would go out of scope and the proxy would stop existing once the action completed, so it seems like your code would start an in-memory proxy, then immediately destroy that object? Maybe spring beans are different, though. Skimming the docs make it look like maybe they are.

If I were doing this, I'd launch the BrowserUp REST proxy as a standalone EXE and avoid using the embedded mode. That would make it easier to debug as it would separate the proxy lifecycle and the proxy debugging from the webserver managing it.
