### ISSUE TITLE
[enhancement] Generate Rest Clients with Swagger CodeGen

### ISSUE THREAD

**Issue by ericbeland** [browserup/browserup-proxy#133]
**Is your feature request related to a problem? Please describe.**

Right now, as a user, I cannot use the new API enhancements with clients in other languages.

**Describe the solution you'd like**

https://swagger.io/tools/swagger-codegen/

Now that we have swagger, we should be able to automatically generate clients using swagger codegen. I'd like to use it to generate Python, Ruby, and Javascript proxy clients. Initially, they can be stored in a /clients/(Ruby|Python|JavaScript) subfolder of this project. After that, we need to create a strategy to push them to RubyGems, NPM, PyPi etc.

**Comment by wing328** [comment]
@ericbeland you may also consider OpenAPI Generator to generate API clients for the REST API.

Disclosure: I'm the top contributor to both OpenAPI Generator and Swagger Codegen

**Comment by ericbeland** [comment]
@wing328 Thanks for chiming in! I was looking around at this yesterday. I think, as a datapoint, the reason I jumped past OpenAPI was when I took a quick glance at the API clients table on the readme, I didn't see JavaScript jump out at me. We're still in the exploratory phases, so pointers are welcome. 

Our use-cases are: 
* Generate static HTML doc UI for github pages or our docs folder
* Auto-generate the REST API clients in Javascript, Ruby, and Python
* Possibly to look into mingling generated/non-generated code as one of our API's should raise language-specific assertion exceptions and it would be neat to figure out if that's possible.

**Comment by wing328** [comment]
>  I didn't see JavaScript jump out at me.

There's a `javascript` client generator. Please give it a try. I'll update the table later to make it clearer that we support `javascript` client generator

**Comment by ericbeland** [comment]
Working in our new proxy here:

**Comment by sankouski-dzmitry** [comment]
should we include rest clients into releases, to host it in maven repository?
