### ISSUE TITLE
[enhancement] Write HAR from server to File

### ISSUE THREAD

**Issue by NScheeren** [browserup/browserup-proxy#143]
Hi all,

I am writing an Arquillian Extension using your Proxy-Server to create a har file. 

Problem: you do not yet have a method for this.

I tried using https://github.com/SmartBear/har-java, which turns out to be kinda tricky.

as a workaround/quick-fix until you can provide such method:
could you use the annotations @JsonPropertyOrder and @JsonProperty in your HarLog and other Har-classes? it would be much easier to use the JsonGenerator to write a file.

**Comment by NScheeren** [comment]
so meanwhile i build this. Works for me, but i´m not sure it´ll work for everyone

private void writeHAR(File harFile, HarLog log) throws IOException {
		String version = log.getVersion();

		DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'hh:mm:ss.SSS'Z'");

		JsonGenerator jsonGenerator = new JsonFactory().createGenerator(harFile, JsonEncoding.UTF8);

		ObjectMapper objectMapper = new ObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL);
		jsonGenerator.setCodec(objectMapper);
		jsonGenerator.useDefaultPrettyPrinter();

		// Begin File
		jsonGenerator.writeStartObject();

		// Begin log
		jsonGenerator.writeFieldName("log");

		// Begin log object
		jsonGenerator.writeStartObject();

		jsonGenerator.writeFieldName("version");
		jsonGenerator.writeObject(version);

		jsonGenerator.writeFieldName("creator");
		jsonGenerator.writeObject(log.getCreator());

		jsonGenerator.writeFieldName("pages");
		// pages field contains an array of objects
		jsonGenerator.writeStartArray();

		// create the objects in the pages array
		for (HarPage page : log.getPages()) {
			jsonGenerator.writeStartObject();

			jsonGenerator.writeFieldName("startedDateTime");

			jsonGenerator.writeObject(dateFormat.format(page.getStartedDateTime()));

			jsonGenerator.writeFieldName("id");
			jsonGenerator.writeObject(page.getId());

			jsonGenerator.writeFieldName("title");
			jsonGenerator.writeObject(page.getTitle());

			jsonGenerator.writeFieldName("pageTimings");
			jsonGenerator.writeObject(page.getPageTimings());

			jsonGenerator.writeEndObject();
		}

		// end of pages array
		jsonGenerator.writeEndArray();

		jsonGenerator.writeFieldName("entries");
		// Begin of entris array
		jsonGenerator.writeStartArray();
		// write object for each entry
		for (HarEntry entry : log.getEntries()) {
			jsonGenerator.writeStartObject();

			jsonGenerator.writeFieldName("startedDateTime");
			jsonGenerator.writeObject(dateFormat.format(entry.getStartedDateTime()));

			jsonGenerator.writeFieldName("time");
			jsonGenerator.writeObject(entry.getTime());

			jsonGenerator.writeFieldName("request");
			jsonGenerator.writeObject(entry.getRequest());

			jsonGenerator.writeFieldName("response");
			jsonGenerator.writeObject(entry.getResponse());

			jsonGenerator.writeFieldName("timings");
			// object timings has multiple fields
			jsonGenerator.writeObject(entry.getTimings());

			jsonGenerator.writeFieldName("serverIPAddress");
			jsonGenerator.writeObject(entry.getServerIPAddress());
			jsonGenerator.writeFieldName("connection");
			jsonGenerator.writeObject(entry.getConnection());
			jsonGenerator.writeFieldName("pageref");
			jsonGenerator.writeObject(entry.getPageref());

			// end entry object
			jsonGenerator.writeEndObject();

		}

		// end of entries Array
		jsonGenerator.writeEndArray();

		// end of log object
		jsonGenerator.writeEndObject();

		// close File
		jsonGenerator.close();
	}

**Comment by margasan** [comment]
@NScheeren original browsermob-proxy has such method. I don't understand why it was deleted.
https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/main/java/net/lightbody/bmp/core/har/Har.java

**Comment by ericbeland** [comment]
We're open to pull requests. I think this was probably removed when we switched to a different HAR representation.
