### ISSUE TITLE
Multiple clients support and can not limit memory question

### ISSUE THREAD

**Issue by jayden-xie** [browserup/browserup-proxy#193]
I want to ask again here, nice to see you forked the formal project.
I have 2 questions:

1. Does one proxy server support multiple clients recording HAR? It's supported from my testing, but I want to confirm it as I see someone is asking this question and trying to spawn separate proxy for each client. https://github.com/lightbody/browsermob-proxy/issues/655

2. I tried to set xxm to limit memory, but the proxy is stuck when memory reaches the limit, it does not accept new requests any more. The proxy is expected to be long-time-running.

**Comment by ericbeland** [comment]
1. yes

2. I'm not sure, can you use more? What is the limit you used?

**Comment by jayden-xie** [comment]
2. Whatever I tried it got stuck in there. The serve got 64G memory, if I do not set any limit, the memory would keep going high to 10G, and it got stuck again, CPU usage of java process goes really high. Is there any other way to limit memory or can get it support long-time-running?

**Comment by asolntsev** [comment]
@jayden-xie can it be caused by this memory leak in littleproxy library? https://github.com/adamfisk/LittleProxy/issues/437

**Comment by Gordiievskyi** [comment]
@jayden-xie Sorry I have a question about multiple client per har and your testing. Lets say I created a proxy on port 4081, and lets say one user from chrome and one user from firefox use it concurrently as a proxy, both access same site www.google.com, and at the end your can retrieve two hars, each har have only one user agents traffic?

The question and the answer are so abstract so I can't understand what exactly can this proxy. But to have described result one should provide extra id except port, and in standalone mode I don't see such an option

**Comment by ericbeland** [comment]
Yes, if I understand you right. It is basically like a proxy factory. Try and see if you can find some examples in the client you're using.
