### ISSUE TITLE
Wrong scope of public api's dependencies

### ISSUE THREAD

**Issue by rosolko** [browserup/browserup-proxy#199]
**Describe the bug**
All public available api's dependencies should be placed in `api` scope

_Note_: If I want to implement `ResponseFilter` I should manually add `io.netty:netty-codec:4.1.43.Final` library to my project. And it can produce library version incompatibility.

**To Reproduce**
1. Try to implement `ResponseFilter`

**Expected behavior**
`io.netty.handler.codec.http.HttpResponse` is available for use

**Screenshots**
Class isn't in `Compile` scope. By default it has `Runtime` scope.

**Please complete the following information:**
 - OS: macOS 10.15.1 (19B88)

**Additional context**
To fix this issue place all public available api and dependencies in `api` scope instead of `implementation`

**Comment by rosolko** [comment]
Also there is a problem with `ittleproxy`. Without directly adding `xyz.rogfam:littleproxy:2.0.0-beta-5` to dependencies I've got an error about missing `HttpFiltersSource` class during `BrowserUpProxyServer` extends.

**Comment by ericbeland** [comment]
We are open to pull requests if you have a fix. We're in the midst of some other implementations at the moment.
