### ISSUE TITLE
Doesn't work as expected with JDK10+

### ISSUE THREAD

**Issue by doublemarket** [browserup/browserup-proxy#245]
**Describe the bug**

When using browserup-proxy with JDK10+, it's not possible to set a custom port when creating a new proxy config. This is because parsing the data in a POST request doesn't work as expected because [mvel](https://github.com/mvel/mvel) which is contained in browserup-proxy can't run with JDK10+ with [an issue](https://github.com/mvel/mvel/issues/159).

**To Reproduce**

Refer to the issue https://github.com/autifyhq/docker-browserup-proxy/issues/2 as well.

1. Start browserup-proxy with JDK10+ (I tested with JDK14).
2. Issue a POST request to `/proxy` with the `'port=8099'` data.
    - The result is same when providing the data with JSON (`{"port":8099}`).
    - Other options as well. I didn't try with every option but `trustAllServers` can't be set as well.
3. browserup-proxy returns a 500 error.

**Expected behavior**

browserup-proxy should return a port number when hitting with the port number.

**Screenshots**

**Please complete the following information:**
 - OS : Ubuntu
 - Browser : curl

**Additional context**

Providing the version info to mvel [by adding a line](https://github.com/mvel/mvel/issues/203#issuecomment-521325155) in the browserup-proxy code is an option.

**Comment by doublemarket** [comment]
Note that this is confirmed with 2.0.1.

**Comment by ericbeland** [comment]
Can you confirm this with the latest and reopen if it still occurs?

**Comment by weendigo** [comment]
I can't figure how to reopen but the #277 was closed as duplicate of this one and that is repro in 2.1.0 and 2.1.1 as well.
