### ISSUE TITLE
Add removeRequestFilter() and removeResponseFilter() methods for flexibility of processing

### ISSUE THREAD

**Issue by vinogradoff** [browserup/browserup-proxy#259]
It was already requested for browsermob-proxy 5 years ago.
Probably something like this:

```
proxy.addRequestFilter("myFilter", myRequestFilter);
//do something using proxy with myRequestFilter
proxy.removeRequestFilter("myFilter");
// do something using proxy without myRequestFilter
```

There are cases where you need some action (e.g. asserts) only for some part of the flow, and then not - or even the opposite of those.

Please comment if there are known workarounds at least

**Comment by ericbeland** [comment]
This is probably a way off as we need to digest our move to mitmproxy first, and we may have to first go backwards in our API before adding to it. I'm closing for now, but we'll keep it in mind as we look at reimplementations.
