### ISSUE TITLE
Support SOCKS upstream proxy (already available in mrog/LittleProxy)

### ISSUE THREAD

**Issue by ghost** [browserup/browserup-proxy#260]
It'd be great to get support for this. This has already been merged here:
https://github.com/mrog/LittleProxy/pull/17

Original pull request:
https://github.com/adamfisk/LittleProxy/pull/417

**Comment by ericbeland** [comment]
We are transitioning to mitm-proxy based implementation instead of littleproxy. I think this may work in that case.
