### ISSUE TITLE
proxy cannot be restarted

### ISSUE THREAD

**Issue by 2x2xplz** [browserup/browserup-proxy#274]
**Describe the bug**
proxy thinks it is in both `started` and `stopped` modes simultaneously. This is a problem because it cannot be restarted (throws an IllegalState error)

**To Reproduce**
Steps to reproduce the behavior (Kotlin):
```
val buProxy : BrowserUpProxyServer = BrowserUpProxyServer().apply { this.start(8002) }
... drive some Selenium code ...
buProxy.stop()
println(buProxy.isStarted && buProxy.isStopped) // returns true
```

**Expected behavior**
after `buProxy.stop()` , I expect `isStarted` to be false, and subsequent `buProxy.start()` command would not throw an "already started" error

**Screenshots**
![image](https://user-images.githubusercontent.com/16587079/83946010-233ec900-a7c3-11ea-8803-eb5d356fd644.png)

**Please complete the following information:**
 - OS: Windows 10 64-bit
 - Chrome (as the webdriver)
 - Version 2.1.1
 - Java 11

**Additional context**
Same behavior exists in BrowserMob. I "upgraded" to BrowserUp, thinking this may have been fixed, but seeing the same issue in both packages.

**Comment by 2x2xplz** [comment]
not sure why I didn't see this earlier, but apparently this behavior is originally by design: https://github.com/lightbody/browsermob-proxy/issues/264#issuecomment-112933259

> BMP is not currently meant to be stopped and restarted.

With that said, this is a new project and new company, perhaps it is worth reconsidering whether no-restarts is the best option, or if it should be implemented.

**Comment by ericbeland** [comment]
We have a new implementation coming out. I'm closing for now. I think we may end up doing this along the way, though.
