### ISSUE TITLE
Adopt appropriate terminology: AllowList and BlockList

### ISSUE THREAD

**Issue by johnjbarton** [browserup/browserup-proxy#281]
Your API should use feature-oriented nouns like 'skip' or 'allow' and phase out antiquated non-descriptive color based names:
https://github.com/browserup/browserup-proxy/search?q=blacklist&unscoped_q=blacklist

Obviously this will require adding the API and deprecating the old usage.

**Comment by ericbeland** [comment]
This should be workable. "Skip" isn't clear to me whether it skips the proxy, or skips making the request. We will use "Allow" list and "Block" list.

The next major release will have some breaking changes to the API as we're moving to wrap mitmproxy in place of littleproxy, so we will ship this at that point.

**Comment by ericbeland** [comment]
PR merged here:  https://github.com/browserup/browserup-proxy/pull/337
