### ISSUE TITLE
Question: Is HTTP/2 supported?

### ISSUE THREAD

**Issue by amjd** [browserup/browserup-proxy#305]
Does BUP support HTTP/2 at this point? From [v1.0.0's release notes](https://github.com/browserup/browserup-proxy/releases/tag/v1.0.0) I figured it does. However, when I tried it with some HTTP/2 websites, the HAR still showed the version as 1.1.

If it is supported, are there any additional steps or settings required to make it work?

**Edit:**
Didn't notice the other issue (#243) earlier as it didn't show up in search.
Could you share an update about the status of HTTP/2 support and whether you've planned any timelines around it.

**Comment by ericbeland** [comment]
Sure! We have an alpha we are working on that uses MITM Proxy and replaces littleproxy. MITM has a python dependency so we are going to have to either require Python as an installation, or possibly use a docker container as the artifact if that makes sense.

Right now, we have it implemented, but are working through some bugs. Packaging it up is still on our to-do. Probably it will be  a couple months before it is baked and released. Beta maybe a little sooner. 

If you want to experiment, let me know and I can email you when this round of issues is fixed.

**Comment by amjd** [comment]
Thanks for the response. Sure, I'd be very interested in checking out the alpha / beta. :) 

You can reach me on amjad.4@gmail.com

**Comment by Gordiievskyi** [comment]
@ericbeland I'de like to experiment, and I think docker is a good solution because it's platform agnostic.But I can't guaranty I will testing asap I receive it, have current project work load
