### ISSUE TITLE
Support for Websockets in browserup proxy

### ISSUE THREAD

**Issue by PAVITHRA001** [browserup/browserup-proxy#356]
I am using standalone mode of browser up proxy using REST API
I read at one your sites, WebSocket will be supported
Is websocket calls supported in browserup proxy, 
If supported how to use it?
If not supported is there a workaround for skipping websocket calls from proxy?

**Comment by ericbeland** [comment]
We had a lot of trouble with websockets and http/2 in the old architecture.  Instead, we have forked mitm proxy, and added some of our functionality on top of it. I you are interested in beta testing, it is on the branch named "main" here:  https://github.com/browserup/mitmproxy

We have clients in Java, Javascript, Ruby and Python.

I can give you instructions if you feel like trying it.

**Comment by ericbeland** [comment]
Oh--it has websocket support working.
