### ISSUE TITLE
assertNoBrokenImages, assertNoBrokenJavascriptLinks etc.

### ISSUE THREAD

**Issue by ericbeland** [browserup/browserup-proxy#54]
I'd like add assertNoBrokenLinks() and assertNoBrokenImages() to our assertions library. For this to work, we need to check every item of the appropriate type. Also perhaps assertNoBrokenJavascriptLinks(), assertNoBrokenStyleLinks(), and finally assertNoBrokenResources(), which asserts that *everything* on the page loaded.

https://www.guru99.com/find-broken-links-selenium-webdriver.html

**Comment by ericbeland** [comment]
For link verification in assertNoBrokenLinks, we will need to make the request, and we should leave those results out of the HAR. Another consideration is that if we are chained to another proxy, we want to be sure we make those requests via that proxy or we would get false broken link results.

**Comment by epic-alex-rodionov** [comment]
@dpowell @ericbeland 

1. Should we validate only internal(which belongs only to domain) links, images, JS files or all?
or we can have 3 methods instead on one: `assertNoBrokenLinks`, `assertNoBrokenInternalLinks`, `assertNoBrokenExternalLinks`?

2. Should we use `assertNoBrokenLinks()` without parameters or we can use it like: `assertNoBrokenLinks(Pattern url)`? Or we need both?

**Comment by dpowell** [comment]
I don’t think “external only” is important, so perhaps `assertNoBrokenLinks(includeExternal=false)`?

**Comment by epic-alex-rodionov** [comment]
Hi @dpowell @ericbeland 
I have a silly question. Are these new assertions part of `browserup-proxy` https://github.com/browserup/browserup-proxy/blob/master/browserup-proxy-core/src/main/java/com/browserup/bup/BrowserUpProxyServer.java which should analyze somehow `har` information, get all entries and check that all statuses have code 200 for required mime-type?
```
{
        "startedDateTime": "2012-08-28T05:14:25.103Z",
        "time": 0,
        "request": {
          "method": "GET",
          "url": "http://www.google-analytics.com/ga.js",
          "httpVersion": "HTTP/1.1",
          "headers": [],
          "queryString": [],
          "cookies": [],
          "headersSize": 52,
          "bodySize": 0
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Mon, 27 Aug 2012 21:57:00 GMT"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "X-Content-Type-Options",
              "value": "nosniff, nosniff"
            },
            {
              "name": "Age",
              "value": "23052"
            },
            {
              "name": "Last-Modified",
              "value": "Thu, 16 Aug 2012 07:05:05 GMT"
            },
            {
              "name": "Server",
              "value": "GFE/2.0"
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "Content-Type",
              "value": "text/javascript"
            },
            {
              "name": "Expires",
              "value": "Tue, 28 Aug 2012 09:57:00 GMT"
            },
            {
              "name": "Cache-Control",
              "value": "max-age=43200, public"
            },
            {
              "name": "Content-Length",
              "value": "14804"
            }
          ],
          "cookies": [],
          "content": {
            "size": 36893,
            "mimeType": "text/javascript"
          },
          "redirectURL": "",
          "headersSize": 17,
          "bodySize": 0
        }
```

Or this is a part of `browserup-driver` like https://github.com/browserup/browserup-driver/blob/master/src/main/java/com/browserup/automation/api/assertions
when we can create something like Eric mentioned above https://www.guru99.com/find-broken-links-selenium-webdriver.html: `new ChromeDriver().findElements(By.tagName("a"))...` and use it like:
```
driver.get("http://browserup.com/blog/category/devops/");
driver.assertNoBrokenLinks();
```

**Comment by ericbeland** [comment]
Not a silly question at all. The assertions will live in the proxy, but be called via the driver. The reason for that is that if we put them in the proxy, we can share this functionality across any of the consuming drivers we publish without rewriting it in 5 languages.

**Comment by dpowell** [comment]
Splitting the link probing out into a separate ticket, leaving this as "check the status of already recorded requests".

**Comment by epic-alex-rodionov** [comment]
@dpowell @ericbeland Do we need REST API here?

**Comment by ericbeland** [comment]
Yes.

**Comment by epic-alex-rodionov** [comment]
PR https://github.com/browserup/browserup-proxy/pull/76 has been merged to https://github.com/browserup/browserup-proxy/tree/next_merge_with_master
