### ISSUE TITLE
Produce zip distribution including shell scripts and dependencies

### ISSUE THREAD

**Issue by gredondogc** [browserup/browserup-proxy#71]
Is there an easy way to download all the binaries and instructions on how to use them?

BrowserMob Proxy had a zip file on the releases with some extra files (sh and bat) and ssl certificates.

**Comment by dpowell** [comment]
The production of the zip artifact of browserup-proxy-dist was lost in the conversion from Maven to Gradle. We need to re-implement this with the [Gradle Distribution Plugin](https://docs.gradle.org/current/userguide/distribution_plugin.html).

https://github.com/browserup/browserup-proxy/blob/41ad94fc6bc6ba89f8aabd5a632565ce5ad2e88e/browsermob-dist/assembly.xml

**Comment by dpowell** [comment]
@gredondogc Sorry for the delay on that, Gradle gave me a bit of a fit to get everything packaged with the appropriate POM information and signing and such. You can now download a zip or tar archive that includes all of the proxy software as well as a startup script and the SSL certificates and keys. Our intention is that this should be packaged and operate in the same way as the BrowserMob Proxy was. Please let us know if you run into any issues getting this up and running!

https://github.com/browserup/browserup-proxy/releases/tag/v1.1.0
