### ISSUE TITLE
Increase/Config Max Response Buffer Size

### ISSUE THREAD

**Issue by baclark774** [browserup/browserup-proxy#77]
Awesome work taking on the bmp proxy support!
One nice enhancement would be to allow for users to specify their own max response sizes:

`private static final int DEFAULT_MAXIMUM_RESPONSE_BUFFER_SIZE = 2097152;`

Currently, the 2Meg cap is too light for video and similarly large responses. My team has been building BMP from source for a while now and increasing this to 20Megs but ideally it'd be great if the user could set this via a flag.

**Comment by dpowell** [comment]
Great suggestion, thanks!

**Comment by matti** [comment]
Agreed, this would be great - I just built my own because of this.

**Comment by CreditTone** [comment]
怎么修改？哪个类？

**Comment by endlesshh** [comment]
> 怎么修改？哪个类？

proxy.addLastHttpFilterFactory(new ResponseFilterAdapter.FilterSource(new ResponseFilter() {
             @Override
             public void filterResponse(HttpResponse response, HttpMessageContents contents, HttpMessageInfo messageInfo) {
             	
            	 
             }
},20971520)

**Comment by Gordiievskyi** [comment]
Hi Guys,

I use BUP in Standalone Mode. How can I configure the size(my stack is node js), I have an error like @CreditTone described on BMP git, and only in case I add response filter. Anyway if there is an endpoint to set the size or workaround I will appreciate

**Comment by ericbeland** [comment]
We recently merged a PR with a hard-coded temporary bump, although we haven't gone as far as making it a config option, which would be nice to do.

**Comment by eric2296** [comment]
How can I increase the response size?
This is how I used  ResponseFilter in my code:

`proxy.addResponseFilter((response, contents, messageInfo) -> {
            /*...*/
});`

**Comment by MisterChangRay** [comment]
add flow code it's work

```java
 browserMobProxy = new BrowserMobProxyServer();
        browserMobProxy.setReadBandwidthLimit(20 * (1024 * 1024));
        browserMobProxy.setWriteBandwidthLimit(20 * (1024 * 1024));
        browserMobProxy.setTrustAllServers(true);

        browserMobProxy.start(0);
        browserMobProxy.addRequestFilter(new ReqFilter(params));
        browserMobProxy.addResponseFilter(new ResFilter(params));
        browserMobProxy.addLastHttpFilterFactory(new HttpFiltersSource() {
            @Override
            public HttpFilters filterRequest(HttpRequest originalRequest, ChannelHandlerContext ctx) {
                return null;
            }

            @Override
            public int getMaximumRequestBufferSizeInBytes() {
                return 20 * (1024 * 1024);
            }

            @Override
            public int getMaximumResponseBufferSizeInBytes() {
                return 20 * (1024 * 1024);
            }
        });
```
