### ISSUE TITLE
WebSocket Support

### ISSUE THREAD

**Issue by dpowell** [browserup/browserup-proxy#8]
Ensure WebSocket connections are proxied properly.

**Comment by Nashati** [comment]
Are there any plans to add this enhancement any time soon?

**Comment by ericbeland** [comment]
Yes, it is the next planned item following getting HTTP/2 support corrected.

**Comment by csharsha** [comment]
any updates on getting HTTP/2 support?

**Comment by evgeny-tumashchick** [comment]
Hi, maybe you have any updates for this enhancement? We wanted to use your proxy as standalone server for our automation tests infrastructure and really impressed by opportunities that it provides. Unfortunately our application under tests using web socket calls, so currently this is a blocker for us :(

**Comment by akaczinski** [comment]
Hi there,
Any updates for this? My current use case just needs to know if Chrome is seeing websocket connections being made. Thanks!

**Comment by ericbeland** [comment]
I'm closing this for now as we at least will be able to pass this traffic around in the next version, and we also have https://github.com/browserup/browserup-proxy/issues/9 to track this.
