### ISSUE TITLE
WebSocket Network Recording

### ISSUE THREAD

**Issue by dpowell** [browserup/browserup-proxy#9]
Collect WebSockets traffic in Proxy (extension to HAR?) for access via APIs for assertions from browserup/browserup-driver.

**Comment by ericbeland** [comment]
It would be best to follow the precent from here:

https://bugs.chromium.org/p/chromium/issues/detail?id=496006

**Comment by ericbeland** [comment]
We had a lot of trouble with websockets and http/2 in the old architecture.  Instead, we have forked mitm proxy, and added some of our functionality on top of it.  In the new iteration of the BrowserUp proxy in our mitmproxy based fork, we capture websocket traffic into the har. Also, it works with HTTP/2.


Anyone interested in beta testing, it is on the branch named "main" here:  https://github.com/browserup/mitmproxy

We have clients in Java, Javascript, Ruby and Python. See clients/examples
