### ISSUE TITLE
Describe REST API with OpenAPI definition

### ISSUE THREAD

**Issue by dpowell** [browserup/browserup-proxy#94]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md

**Comment by ericbeland** [comment]
This may go without saying, but there's a great HTML/markdown table on the README that has doc with descriptions and parameter descriptions that we can populate the swagger code descriptions with once the endpoints are in an annotatable format. 

Once we can generate swagger doc, I'd also like to remove the HTML table hogging up space in our README. Then we just have the challenge of building the swagger doc and putting it somewhere every build, probably via CI/CD.

https://github.com/browserup/browserup-proxy
